#!/bin/sh

echo -n "checking for linker (gcc)... "
if which gcc >/dev/null ; then
	echo yes ; ld="gcc"
else
	echo no

	echo -n "checking for linker (ld)... "
	if which gcc >/dev/null ; then
		echo yes ; ld="ld"
	else
		echo "error: no linker found"
		exit 1
	fi
fi

BMAKE_DECL="$BMAKE_DECL\
bmake_LD = $ld
"
