#!/bin/sh

echo -n "checking for compiler (${toolchain}gcc)... "
if which "${toolchainL}gcc" >/dev/null ; then
	echo yes ; cc="${toolchain}gcc"
else
	echo no

	echo -n "checking for compiler (${toolchain}cc)... "
	if which "${toolchain}gcc" >/dev/null ; then
		echo yes ; cc="${toolchain}cc"
	else
		echo "error: no compiler found"
		exit 1
	fi
fi

BMAKE_DECL="${BMAKE_DECL}\
bmake_CC = $cc
bmake_PRECC += @if [ ! -d \"\$(@D)/deps\" ] ; then mkdir \"\$(@D)/deps\" ; fi
bmake_CFLAGS += -MD -MP -MF \$(@D)/deps/\$(@F).dep
"
