#!/bin/sh

echo -n "checking for compiler (gcc)... "
if which gcc >/dev/null ; then
	echo yes ; cc="gcc"
else
	echo no

	echo -n "checking for compiler (cc)... "
	if which gcc >/dev/null ; then
		echo yes ; cc="cc"
	else
		echo "error: no compiler found"
		exit 1
	fi
fi

BMAKE_DECL="${BMAKE_DECL}\
bmake_CC = $cc
bmake_PRECC += @if [ ! -d \"\$(@D)/deps\" ] ; then mkdir \"\$(@D)/deps\" ; fi
bmake_CFLAGS += -MD -MP -MF \$(@D)/deps/\$(@F).dep
"
