#!/bin/sh

echo -n "checking for linker (${toolchain}gcc)... "
if which "${toolchain}gcc" >/dev/null ; then
	echo yes ; ld="${toolchain}gcc"
else
	echo no

	echo -n "checking for linker (${toolchain}ld)... "
	if which "${toolchain}gcc" >/dev/null ; then
		echo yes ; ld="${toolchain}ld"
	else
		echo "error: no linker found"
		exit 1
	fi
fi

BMAKE_DECL="${BMAKE_DECL}\
bmake_LD = $ld
"
