#!/bin/sh

##
# Linker Test
#   Verifies that the current machine and toolchain have a linker installed.
# Variables
#   ld
#     Set to the available linker.
#.

echo -n "checking for linker (${toolchain}gcc)... "
if which "${toolchain}gcc" >/dev/null ; then
	echo yes ; ld="${toolchain}gcc"
else
	echo no

	echo -n "checking for linker (${toolchain}ld)... "
	if which "${toolchain}gcc" >/dev/null ; then
		echo yes ; ld="${toolchain}ld"
	else
		echo "error: no linker found"
		exit 1
	fi
fi
